package edu.luc.comp433.service.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import edu.luc.comp433.service.OrderService;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2014-10-03T17:27:07.857-05:00
 * Generated source version: 2.7.12
 * 
 */
@WebServiceClient(name = "OrderServiceImplService", 
                  wsdlLocation = "http://localhost:8080/project2/Order?wsdl",
                  targetNamespace = "http://impl.service.comp433.luc.edu/") 
public class OrderServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.service.comp433.luc.edu/", "OrderServiceImplService");
    public final static QName OrderServiceImplPort = new QName("http://impl.service.comp433.luc.edu/", "OrderServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/project2/Order?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(OrderServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/project2/Order?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public OrderServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OrderServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrderServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OrderServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OrderServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OrderServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns OrderService
     */
    @WebEndpoint(name = "OrderServiceImplPort")
    public OrderService getOrderServiceImplPort() {
        return super.getPort(OrderServiceImplPort, OrderService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrderService
     */
    @WebEndpoint(name = "OrderServiceImplPort")
    public OrderService getOrderServiceImplPort(WebServiceFeature... features) {
        return super.getPort(OrderServiceImplPort, OrderService.class, features);
    }

}
