
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package edu.luc.comp433.service;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2014-09-30T13:37:23.122-05:00
 * Generated source version: 2.7.12
 * 
 */

@javax.jws.WebService(
                      serviceName = "AddressServiceImplService",
                      portName = "AddressServiceImplPort",
                      targetNamespace = "http://impl.service.comp433.luc.edu/",
                      wsdlLocation = "http://localhost:8080/project2/Address?wsdl",
                      endpointInterface = "edu.luc.comp433.service.AddressService")
                      
public class AddressServiceImpl implements AddressService {

    private static final Logger LOG = Logger.getLogger(AddressServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see edu.luc.comp433.service.AddressService#findAddressById(java.lang.Short  arg0 )*
     */
    public edu.luc.comp433.service.Address findAddressById(java.lang.Short arg0) { 
        LOG.info("Executing operation findAddressById");
        System.out.println(arg0);
        try {
            edu.luc.comp433.service.Address _return = new edu.luc.comp433.service.Address();
            _return.setCity("City1151198911");
            _return.setComplement("Complement-200270661");
            _return.setId(Short.valueOf((short)4393));
            _return.setNumber("Number1714080604");
            java.util.List<edu.luc.comp433.service.Order> _returnOrderList = new java.util.ArrayList<edu.luc.comp433.service.Order>();
            edu.luc.comp433.service.Order _returnOrderListVal1 = new edu.luc.comp433.service.Order();
            edu.luc.comp433.service.Address _returnOrderListVal1Address = new edu.luc.comp433.service.Address();
            _returnOrderListVal1Address.setCity("City-1161956258");
            _returnOrderListVal1Address.setComplement("Complement480217387");
            _returnOrderListVal1Address.setId(Short.valueOf((short)-27478));
            _returnOrderListVal1Address.setNumber("Number-1461620289");
            java.util.List<edu.luc.comp433.service.Order> _returnOrderListVal1AddressOrderList = new java.util.ArrayList<edu.luc.comp433.service.Order>();
            _returnOrderListVal1Address.getOrderList().addAll(_returnOrderListVal1AddressOrderList);
            _returnOrderListVal1Address.setState("State579393129");
            _returnOrderListVal1Address.setStreet("Street-2117192928");
            _returnOrderListVal1Address.setZipcode(-37769612);
            _returnOrderListVal1.setAddress(_returnOrderListVal1Address);
            edu.luc.comp433.service.Customer _returnOrderListVal1Customer = new edu.luc.comp433.service.Customer();
            _returnOrderListVal1Customer.setId(Short.valueOf((short)27170));
            _returnOrderListVal1Customer.setLogin("Login-1571017393");
            _returnOrderListVal1Customer.setName("Name-1701764444");
            _returnOrderListVal1Customer.setPassword("Password1598682920");
            _returnOrderListVal1.setCustomer(_returnOrderListVal1Customer);
            _returnOrderListVal1.setId(Short.valueOf((short)-9963));
            edu.luc.comp433.service.Payment _returnOrderListVal1Payment = new edu.luc.comp433.service.Payment();
            _returnOrderListVal1Payment.setAmount(new java.math.BigDecimal("3479696913289993451.4510416718333779977"));
            _returnOrderListVal1Payment.setCardHolderName("CardHolderName-8805138");
            _returnOrderListVal1Payment.setCardNumber("CardNumber647521461");
            edu.luc.comp433.service.Customer _returnOrderListVal1PaymentCustomer = new edu.luc.comp433.service.Customer();
            _returnOrderListVal1PaymentCustomer.setId(Short.valueOf((short)-17192));
            _returnOrderListVal1PaymentCustomer.setLogin("Login2044702213");
            _returnOrderListVal1PaymentCustomer.setName("Name1335651755");
            _returnOrderListVal1PaymentCustomer.setPassword("Password1838472439");
            _returnOrderListVal1Payment.setCustomer(_returnOrderListVal1PaymentCustomer);
            _returnOrderListVal1Payment.setExpirationMonth(-435335911);
            _returnOrderListVal1Payment.setExpirationYear(-25911918);
            _returnOrderListVal1Payment.setId(Short.valueOf((short)-8204));
            _returnOrderListVal1Payment.setSecurityCode(-1083166279);
            _returnOrderListVal1.setPayment(_returnOrderListVal1Payment);
            edu.luc.comp433.service.OrderStatus _returnOrderListVal1Status = edu.luc.comp433.service.OrderStatus.PROCESSING;
            _returnOrderListVal1.setStatus(_returnOrderListVal1Status);
            _returnOrderList.add(_returnOrderListVal1);
            _return.getOrderList().addAll(_returnOrderList);
            _return.setState("State-1268620905");
            _return.setStreet("Street-1960257195");
            _return.setZipcode(161901377);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see edu.luc.comp433.service.AddressService#findAddressByCustomerId(java.lang.Short  arg0 )*
     */
    public java.util.List<edu.luc.comp433.service.Address> findAddressByCustomerId(java.lang.Short arg0) { 
        LOG.info("Executing operation findAddressByCustomerId");
        System.out.println(arg0);
        try {
            java.util.List<edu.luc.comp433.service.Address> _return = new java.util.ArrayList<edu.luc.comp433.service.Address>();
            edu.luc.comp433.service.Address _returnVal1 = new edu.luc.comp433.service.Address();
            _returnVal1.setCity("City588801542");
            _returnVal1.setComplement("Complement1589151598");
            _returnVal1.setId(Short.valueOf((short)-14963));
            _returnVal1.setNumber("Number1022857073");
            java.util.List<edu.luc.comp433.service.Order> _returnVal1OrderList = new java.util.ArrayList<edu.luc.comp433.service.Order>();
            edu.luc.comp433.service.Order _returnVal1OrderListVal1 = new edu.luc.comp433.service.Order();
            edu.luc.comp433.service.Address _returnVal1OrderListVal1Address = new edu.luc.comp433.service.Address();
            _returnVal1OrderListVal1Address.setCity("City-1078529205");
            _returnVal1OrderListVal1Address.setComplement("Complement531222746");
            _returnVal1OrderListVal1Address.setId(Short.valueOf((short)2620));
            _returnVal1OrderListVal1Address.setNumber("Number-1548208787");
            java.util.List<edu.luc.comp433.service.Order> _returnVal1OrderListVal1AddressOrderList = new java.util.ArrayList<edu.luc.comp433.service.Order>();
            _returnVal1OrderListVal1Address.getOrderList().addAll(_returnVal1OrderListVal1AddressOrderList);
            _returnVal1OrderListVal1Address.setState("State-463689356");
            _returnVal1OrderListVal1Address.setStreet("Street-1294128566");
            _returnVal1OrderListVal1Address.setZipcode(-1543308838);
            _returnVal1OrderListVal1.setAddress(_returnVal1OrderListVal1Address);
            edu.luc.comp433.service.Customer _returnVal1OrderListVal1Customer = new edu.luc.comp433.service.Customer();
            _returnVal1OrderListVal1Customer.setId(Short.valueOf((short)12160));
            _returnVal1OrderListVal1Customer.setLogin("Login-861893828");
            _returnVal1OrderListVal1Customer.setName("Name1205944670");
            _returnVal1OrderListVal1Customer.setPassword("Password-670203413");
            _returnVal1OrderListVal1.setCustomer(_returnVal1OrderListVal1Customer);
            _returnVal1OrderListVal1.setId(Short.valueOf((short)28480));
            edu.luc.comp433.service.Payment _returnVal1OrderListVal1Payment = new edu.luc.comp433.service.Payment();
            _returnVal1OrderListVal1Payment.setAmount(new java.math.BigDecimal("4755980964363272106.3356598373828495343"));
            _returnVal1OrderListVal1Payment.setCardHolderName("CardHolderName-199466561");
            _returnVal1OrderListVal1Payment.setCardNumber("CardNumber1336634809");
            edu.luc.comp433.service.Customer _returnVal1OrderListVal1PaymentCustomer = new edu.luc.comp433.service.Customer();
            _returnVal1OrderListVal1PaymentCustomer.setId(Short.valueOf((short)11424));
            _returnVal1OrderListVal1PaymentCustomer.setLogin("Login578450212");
            _returnVal1OrderListVal1PaymentCustomer.setName("Name-1302352879");
            _returnVal1OrderListVal1PaymentCustomer.setPassword("Password601604692");
            _returnVal1OrderListVal1Payment.setCustomer(_returnVal1OrderListVal1PaymentCustomer);
            _returnVal1OrderListVal1Payment.setExpirationMonth(-1221632296);
            _returnVal1OrderListVal1Payment.setExpirationYear(1812429738);
            _returnVal1OrderListVal1Payment.setId(Short.valueOf((short)-17892));
            _returnVal1OrderListVal1Payment.setSecurityCode(1448256003);
            _returnVal1OrderListVal1.setPayment(_returnVal1OrderListVal1Payment);
            edu.luc.comp433.service.OrderStatus _returnVal1OrderListVal1Status = edu.luc.comp433.service.OrderStatus.SHIPPED;
            _returnVal1OrderListVal1.setStatus(_returnVal1OrderListVal1Status);
            _returnVal1OrderList.add(_returnVal1OrderListVal1);
            _returnVal1.getOrderList().addAll(_returnVal1OrderList);
            _returnVal1.setState("State1509782183");
            _returnVal1.setStreet("Street-1126167180");
            _returnVal1.setZipcode(2090914515);
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
