
package edu.luc.comp433.service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import edu.luc.comp433.service.impl.AddressServiceImplService;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2014-09-30T13:37:23.014-05:00
 * Generated source version: 2.7.12
 * 
 */
public final class AddressService_AddressServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.service.comp433.luc.edu/", "AddressServiceImplService");

    private AddressService_AddressServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = AddressServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        AddressServiceImplService ss = new AddressServiceImplService(wsdlURL, SERVICE_NAME);
        AddressService port = ss.getAddressServiceImplPort();  
        
        {
        System.out.println("Invoking findAddressById...");
        java.lang.Short _findAddressById_arg0 = Short.valueOf((short)2681);
        edu.luc.comp433.service.Address _findAddressById__return = port.findAddressById(_findAddressById_arg0);
        System.out.println("findAddressById.result=" + _findAddressById__return);


        }
        {
        System.out.println("Invoking findAddressByCustomerId...");
        java.lang.Short _findAddressByCustomerId_arg0 = Short.valueOf((short)-31107);
        java.util.List<edu.luc.comp433.service.Address> _findAddressByCustomerId__return = port.findAddressByCustomerId(_findAddressByCustomerId_arg0);
        System.out.println("findAddressByCustomerId.result=" + _findAddressByCustomerId__return);


        }

        System.exit(0);
    }

}
