package edu.luc.comp433.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2014-09-30T13:37:23.162-05:00
 * Generated source version: 2.7.12
 * 
 */
@WebService(targetNamespace = "http://service.comp433.luc.edu/", name = "AddressService")
@XmlSeeAlso({ObjectFactory.class})
public interface AddressService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findAddressById", targetNamespace = "http://service.comp433.luc.edu/", className = "edu.luc.comp433.service.FindAddressById")
    @WebMethod
    @ResponseWrapper(localName = "findAddressByIdResponse", targetNamespace = "http://service.comp433.luc.edu/", className = "edu.luc.comp433.service.FindAddressByIdResponse")
    public edu.luc.comp433.service.Address findAddressById(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Short arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findAddressByCustomerId", targetNamespace = "http://service.comp433.luc.edu/", className = "edu.luc.comp433.service.FindAddressByCustomerId")
    @WebMethod
    @ResponseWrapper(localName = "findAddressByCustomerIdResponse", targetNamespace = "http://service.comp433.luc.edu/", className = "edu.luc.comp433.service.FindAddressByCustomerIdResponse")
    public java.util.List<edu.luc.comp433.service.Address> findAddressByCustomerId(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Short arg0
    );
}
