
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package edu.luc.comp433.service;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2014-09-30T13:36:37.694-05:00
 * Generated source version: 2.7.12
 * 
 */

@javax.jws.WebService(
                      serviceName = "BookServiceImplService",
                      portName = "BookServiceImplPort",
                      targetNamespace = "http://impl.service.comp433.luc.edu/",
                      wsdlLocation = "http://localhost:8080/project2/Book?wsdl",
                      endpointInterface = "edu.luc.comp433.service.BookService")
                      
public class BookServiceImpl implements BookService {

    private static final Logger LOG = Logger.getLogger(BookServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see edu.luc.comp433.service.BookService#listAllBooks(*
     */
    public java.util.List<edu.luc.comp433.service.Book> listAllBooks() { 
        LOG.info("Executing operation listAllBooks");
        try {
            java.util.List<edu.luc.comp433.service.Book> _return = new java.util.ArrayList<edu.luc.comp433.service.Book>();
            edu.luc.comp433.service.Book _returnVal1 = new edu.luc.comp433.service.Book();
            _returnVal1.setAuthor("Author-2089650444");
            _returnVal1.setId(Short.valueOf((short)-21718));
            _returnVal1.setPrice(new java.math.BigDecimal("4254098363286014371.7094817532536980688"));
            _returnVal1.setTitle("Title131394413");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see edu.luc.comp433.service.BookService#searchBookByIds(java.util.List<java.lang.Short>  arg0 )*
     */
    public java.util.List<edu.luc.comp433.service.Book> searchBookByIds(java.util.List<java.lang.Short> arg0) { 
        LOG.info("Executing operation searchBookByIds");
        System.out.println(arg0);
        try {
            java.util.List<edu.luc.comp433.service.Book> _return = new java.util.ArrayList<edu.luc.comp433.service.Book>();
            edu.luc.comp433.service.Book _returnVal1 = new edu.luc.comp433.service.Book();
            _returnVal1.setAuthor("Author1980714112");
            _returnVal1.setId(Short.valueOf((short)-10875));
            _returnVal1.setPrice(new java.math.BigDecimal("2565512543746018035.2997784600780236681"));
            _returnVal1.setTitle("Title-446922746");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see edu.luc.comp433.service.BookService#searchBookByTitle(java.lang.String  arg0 )*
     */
    public java.util.List<edu.luc.comp433.service.Book> searchBookByTitle(java.lang.String arg0) { 
        LOG.info("Executing operation searchBookByTitle");
        System.out.println(arg0);
        try {
            java.util.List<edu.luc.comp433.service.Book> _return = new java.util.ArrayList<edu.luc.comp433.service.Book>();
            edu.luc.comp433.service.Book _returnVal1 = new edu.luc.comp433.service.Book();
            _returnVal1.setAuthor("Author700351316");
            _returnVal1.setId(Short.valueOf((short)30539));
            _returnVal1.setPrice(new java.math.BigDecimal("-6048493751452484050.8492952795322301264"));
            _returnVal1.setTitle("Title-346744539");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see edu.luc.comp433.service.BookService#searchBookByPrice(java.math.BigDecimal  arg0 ,)java.math.BigDecimal  arg1 )*
     */
    public java.util.List<edu.luc.comp433.service.Book> searchBookByPrice(java.math.BigDecimal arg0,java.math.BigDecimal arg1) { 
        LOG.info("Executing operation searchBookByPrice");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            java.util.List<edu.luc.comp433.service.Book> _return = new java.util.ArrayList<edu.luc.comp433.service.Book>();
            edu.luc.comp433.service.Book _returnVal1 = new edu.luc.comp433.service.Book();
            _returnVal1.setAuthor("Author-953814383");
            _returnVal1.setId(Short.valueOf((short)-31617));
            _returnVal1.setPrice(new java.math.BigDecimal("3801104667120681995.6098891873739573068"));
            _returnVal1.setTitle("Title1389580869");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see edu.luc.comp433.service.BookService#searchBookByAuthor(java.lang.String  arg0 )*
     */
    public java.util.List<edu.luc.comp433.service.Book> searchBookByAuthor(java.lang.String arg0) { 
        LOG.info("Executing operation searchBookByAuthor");
        System.out.println(arg0);
        try {
            java.util.List<edu.luc.comp433.service.Book> _return = new java.util.ArrayList<edu.luc.comp433.service.Book>();
            edu.luc.comp433.service.Book _returnVal1 = new edu.luc.comp433.service.Book();
            _returnVal1.setAuthor("Author-1520958680");
            _returnVal1.setId(Short.valueOf((short)-24711));
            _returnVal1.setPrice(new java.math.BigDecimal("-3727130015931957072.1957170981972661880"));
            _returnVal1.setTitle("Title175635757");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
