
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package edu.luc.comp433.service;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2014-09-30T13:37:01.392-05:00
 * Generated source version: 2.7.12
 * 
 */

@javax.jws.WebService(
                      serviceName = "CustomerServiceImplService",
                      portName = "CustomerServiceImplPort",
                      targetNamespace = "http://impl.service.comp433.luc.edu/",
                      wsdlLocation = "http://localhost:8080/project2/Customer?wsdl",
                      endpointInterface = "edu.luc.comp433.service.CustomerService")
                      
public class CustomerServiceImpl implements CustomerService {

    private static final Logger LOG = Logger.getLogger(CustomerServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see edu.luc.comp433.service.CustomerService#findCustomerByLogin(java.lang.String  arg0 )*
     */
    public edu.luc.comp433.service.Customer findCustomerByLogin(java.lang.String arg0) { 
        LOG.info("Executing operation findCustomerByLogin");
        System.out.println(arg0);
        try {
            edu.luc.comp433.service.Customer _return = new edu.luc.comp433.service.Customer();
            _return.setId(Short.valueOf((short)-14862));
            _return.setLogin("Login-1026095348");
            _return.setName("Name978578984");
            _return.setPassword("Password-225834488");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see edu.luc.comp433.service.CustomerService#createOrUpdateCustomer(edu.luc.comp433.service.Customer  arg0 ,)edu.luc.comp433.service.Address  arg1 ,)edu.luc.comp433.service.Payment  arg2 )*
     */
    public edu.luc.comp433.service.Customer createOrUpdateCustomer(edu.luc.comp433.service.Customer arg0,edu.luc.comp433.service.Address arg1,edu.luc.comp433.service.Payment arg2) { 
        LOG.info("Executing operation createOrUpdateCustomer");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        try {
            edu.luc.comp433.service.Customer _return = new edu.luc.comp433.service.Customer();
            _return.setId(Short.valueOf((short)14550));
            _return.setLogin("Login1029418686");
            _return.setName("Name-174098494");
            _return.setPassword("Password-1959017849");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
