package edu.luc.comp433.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2014-09-30T13:37:01.417-05:00
 * Generated source version: 2.7.12
 * 
 */
@WebService(targetNamespace = "http://service.comp433.luc.edu/", name = "CustomerService")
@XmlSeeAlso({ObjectFactory.class})
public interface CustomerService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findCustomerByLogin", targetNamespace = "http://service.comp433.luc.edu/", className = "edu.luc.comp433.service.FindCustomerByLogin")
    @WebMethod
    @ResponseWrapper(localName = "findCustomerByLoginResponse", targetNamespace = "http://service.comp433.luc.edu/", className = "edu.luc.comp433.service.FindCustomerByLoginResponse")
    public edu.luc.comp433.service.Customer findCustomerByLogin(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "createOrUpdateCustomer", targetNamespace = "http://service.comp433.luc.edu/", className = "edu.luc.comp433.service.CreateOrUpdateCustomer")
    @WebMethod
    @ResponseWrapper(localName = "createOrUpdateCustomerResponse", targetNamespace = "http://service.comp433.luc.edu/", className = "edu.luc.comp433.service.CreateOrUpdateCustomerResponse")
    public edu.luc.comp433.service.Customer createOrUpdateCustomer(
        @WebParam(name = "arg0", targetNamespace = "")
        edu.luc.comp433.service.Customer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        edu.luc.comp433.service.Address arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        edu.luc.comp433.service.Payment arg2
    );
}
