package edu.luc.comp433.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2014-10-03T17:27:07.840-05:00
 * Generated source version: 2.7.12
 * 
 */
@WebService(targetNamespace = "http://service.comp433.luc.edu/", name = "OrderService")
@XmlSeeAlso({ObjectFactory.class})
public interface OrderService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "createOrder", targetNamespace = "http://service.comp433.luc.edu/", className = "edu.luc.comp433.service.CreateOrder")
    @WebMethod
    @ResponseWrapper(localName = "createOrderResponse", targetNamespace = "http://service.comp433.luc.edu/", className = "edu.luc.comp433.service.CreateOrderResponse")
    public java.lang.Short createOrder(
        @WebParam(name = "arg0", targetNamespace = "")
        edu.luc.comp433.service.Customer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        edu.luc.comp433.service.Address arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.util.List<edu.luc.comp433.service.Book> arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        edu.luc.comp433.service.Payment arg3
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "checkOrderStatus", targetNamespace = "http://service.comp433.luc.edu/", className = "edu.luc.comp433.service.CheckOrderStatus")
    @WebMethod
    @ResponseWrapper(localName = "checkOrderStatusResponse", targetNamespace = "http://service.comp433.luc.edu/", className = "edu.luc.comp433.service.CheckOrderStatusResponse")
    public edu.luc.comp433.service.OrderStatus checkOrderStatus(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Short arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findOrderByCustomerLogin", targetNamespace = "http://service.comp433.luc.edu/", className = "edu.luc.comp433.service.FindOrderByCustomerLogin")
    @WebMethod
    @ResponseWrapper(localName = "findOrderByCustomerLoginResponse", targetNamespace = "http://service.comp433.luc.edu/", className = "edu.luc.comp433.service.FindOrderByCustomerLoginResponse")
    public java.util.List<edu.luc.comp433.service.Order> findOrderByCustomerLogin(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

	@WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "cancelOrder", targetNamespace = "http://service.comp433.luc.edu/", className = "edu.luc.comp433.service.CancelOrder")
    @WebMethod
    @ResponseWrapper(localName = "cancelOrderResponse", targetNamespace = "http://service.comp433.luc.edu/", className = "edu.luc.comp433.service.CancelOrderResponse")
    public java.lang.Boolean cancelOrder(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Short arg0
    );
}
