
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package edu.luc.comp433.service;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2014-10-03T17:27:07.811-05:00
 * Generated source version: 2.7.12
 * 
 */

@javax.jws.WebService(
                      serviceName = "OrderServiceImplService",
                      portName = "OrderServiceImplPort",
                      targetNamespace = "http://impl.service.comp433.luc.edu/",
                      wsdlLocation = "http://localhost:8080/project2/Order?wsdl",
                      endpointInterface = "edu.luc.comp433.service.OrderService")
                      
public class OrderServiceImpl implements OrderService {

    private static final Logger LOG = Logger.getLogger(OrderServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see edu.luc.comp433.service.OrderService#createOrder(edu.luc.comp433.service.Customer  arg0 ,)edu.luc.comp433.service.Address  arg1 ,)java.util.List<edu.luc.comp433.service.Book>  arg2 ,)edu.luc.comp433.service.Payment  arg3 )*
     */
    public java.lang.Short createOrder(edu.luc.comp433.service.Customer arg0,edu.luc.comp433.service.Address arg1,java.util.List<edu.luc.comp433.service.Book> arg2,edu.luc.comp433.service.Payment arg3) { 
        LOG.info("Executing operation createOrder");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        System.out.println(arg3);
        try {
            java.lang.Short _return = Short.valueOf((short)23516);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see edu.luc.comp433.service.OrderService#checkOrderStatus(java.lang.Short  arg0 )*
     */
    public edu.luc.comp433.service.OrderStatus checkOrderStatus(java.lang.Short arg0) { 
        LOG.info("Executing operation checkOrderStatus");
        System.out.println(arg0);
        try {
            edu.luc.comp433.service.OrderStatus _return = edu.luc.comp433.service.OrderStatus.PROCESSING;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    public java.util.List<edu.luc.comp433.service.Order> findOrderByCustomerLogin(java.lang.String arg0) { 
        LOG.info("Executing operation findOrderByCustomerLogin");
        System.out.println(arg0);
        try {
            java.util.List<edu.luc.comp433.service.Order> _return = new java.util.ArrayList<edu.luc.comp433.service.Order>();
            edu.luc.comp433.service.Order _returnVal1 = new edu.luc.comp433.service.Order();
            edu.luc.comp433.service.Address _returnVal1Address = new edu.luc.comp433.service.Address();
            _returnVal1Address.setCity("City1590192684");
            _returnVal1Address.setComplement("Complement-1234337066");
            _returnVal1Address.setId(Short.valueOf((short)16968));
            _returnVal1Address.setNumber("Number893145810");
            java.util.List<edu.luc.comp433.service.Order> _returnVal1AddressOrderList = new java.util.ArrayList<edu.luc.comp433.service.Order>();
            _returnVal1Address.getOrderList().addAll(_returnVal1AddressOrderList);
            _returnVal1Address.setState("State1995919237");
            _returnVal1Address.setStreet("Street388940214");
            _returnVal1Address.setZipcode(1275537379);
            _returnVal1.setAddress(_returnVal1Address);
            edu.luc.comp433.service.Customer _returnVal1Customer = new edu.luc.comp433.service.Customer();
            _returnVal1Customer.setId(Short.valueOf((short)-3649));
            _returnVal1Customer.setLogin("Login541605018");
            _returnVal1Customer.setName("Name-58294363");
            _returnVal1Customer.setPassword("Password745448968");
            _returnVal1.setCustomer(_returnVal1Customer);
            _returnVal1.setId(Short.valueOf((short)-30804));
            edu.luc.comp433.service.Payment _returnVal1Payment = new edu.luc.comp433.service.Payment();
            _returnVal1Payment.setAmount(new java.math.BigDecimal("-8074677515648730692.9035292558934214793"));
            _returnVal1Payment.setCardHolderName("CardHolderName359225472");
            _returnVal1Payment.setCardNumber("CardNumber-1730301172");
            edu.luc.comp433.service.Customer _returnVal1PaymentCustomer = new edu.luc.comp433.service.Customer();
            _returnVal1PaymentCustomer.setId(Short.valueOf((short)15204));
            _returnVal1PaymentCustomer.setLogin("Login-1288311593");
            _returnVal1PaymentCustomer.setName("Name-1920436470");
            _returnVal1PaymentCustomer.setPassword("Password739774742");
            _returnVal1Payment.setCustomer(_returnVal1PaymentCustomer);
            _returnVal1Payment.setExpirationMonth(1015603817);
            _returnVal1Payment.setExpirationYear(-1453660874);
            _returnVal1Payment.setId(Short.valueOf((short)16522));
            _returnVal1Payment.setSecurityCode(764332928);
            edu.luc.comp433.service.PaymentType _returnVal1PaymentType = edu.luc.comp433.service.PaymentType.DEBIT;
            _returnVal1Payment.setType(_returnVal1PaymentType);
            _returnVal1.setPayment(_returnVal1Payment);
            edu.luc.comp433.service.OrderStatus _returnVal1Status = edu.luc.comp433.service.OrderStatus.PROCESSING;
            _returnVal1.setStatus(_returnVal1Status);
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

	/* (non-Javadoc)
     * @see edu.luc.comp433.service.OrderService#cancelOrder(java.lang.Short  arg0 )*
     */
    public java.lang.Boolean cancelOrder(java.lang.Short arg0) { 
        LOG.info("Executing operation cancelOrder");
        System.out.println(arg0);
        try {
            java.lang.Boolean _return = Boolean.valueOf(false);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
