
package edu.luc.comp433.service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import edu.luc.comp433.service.impl.OrderServiceImplService;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2014-10-03T17:27:07.694-05:00
 * Generated source version: 2.7.12
 * 
 */
public final class OrderService_OrderServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.service.comp433.luc.edu/", "OrderServiceImplService");

    private OrderService_OrderServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = OrderServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        OrderServiceImplService ss = new OrderServiceImplService(wsdlURL, SERVICE_NAME);
        OrderService port = ss.getOrderServiceImplPort();  
        
        {
        System.out.println("Invoking createOrder...");
        edu.luc.comp433.service.Customer _createOrder_arg0 = new edu.luc.comp433.service.Customer();
        _createOrder_arg0.setId(Short.valueOf((short)-11388));
        _createOrder_arg0.setLogin("Login-1729718258");
        _createOrder_arg0.setName("Name-17008005");
        _createOrder_arg0.setPassword("Password164648762");
        edu.luc.comp433.service.Address _createOrder_arg1 = new edu.luc.comp433.service.Address();
        _createOrder_arg1.setCity("City-657222169");
        _createOrder_arg1.setComplement("Complement-261299535");
        _createOrder_arg1.setId(Short.valueOf((short)-28137));
        _createOrder_arg1.setNumber("Number464426023");
        java.util.List<edu.luc.comp433.service.Order> _createOrder_arg1OrderList = new java.util.ArrayList<edu.luc.comp433.service.Order>();
        edu.luc.comp433.service.Order _createOrder_arg1OrderListVal1 = new edu.luc.comp433.service.Order();
        edu.luc.comp433.service.Address _createOrder_arg1OrderListVal1Address = new edu.luc.comp433.service.Address();
        _createOrder_arg1OrderListVal1Address.setCity("City381201253");
        _createOrder_arg1OrderListVal1Address.setComplement("Complement1667843160");
        _createOrder_arg1OrderListVal1Address.setId(Short.valueOf((short)17626));
        _createOrder_arg1OrderListVal1Address.setNumber("Number-635598288");
        java.util.List<edu.luc.comp433.service.Order> _createOrder_arg1OrderListVal1AddressOrderList = new java.util.ArrayList<edu.luc.comp433.service.Order>();
        _createOrder_arg1OrderListVal1Address.getOrderList().addAll(_createOrder_arg1OrderListVal1AddressOrderList);
        _createOrder_arg1OrderListVal1Address.setState("State1118509371");
        _createOrder_arg1OrderListVal1Address.setStreet("Street1479115160");
        _createOrder_arg1OrderListVal1Address.setZipcode(-458711502);
        _createOrder_arg1OrderListVal1.setAddress(_createOrder_arg1OrderListVal1Address);
        edu.luc.comp433.service.Customer _createOrder_arg1OrderListVal1Customer = new edu.luc.comp433.service.Customer();
        _createOrder_arg1OrderListVal1Customer.setId(Short.valueOf((short)10753));
        _createOrder_arg1OrderListVal1Customer.setLogin("Login514615976");
        _createOrder_arg1OrderListVal1Customer.setName("Name1383632144");
        _createOrder_arg1OrderListVal1Customer.setPassword("Password-614617966");
        _createOrder_arg1OrderListVal1.setCustomer(_createOrder_arg1OrderListVal1Customer);
        _createOrder_arg1OrderListVal1.setId(Short.valueOf((short)-26584));
        edu.luc.comp433.service.Payment _createOrder_arg1OrderListVal1Payment = new edu.luc.comp433.service.Payment();
        _createOrder_arg1OrderListVal1Payment.setAmount(new java.math.BigDecimal("76710446978135975.1205810648788001020"));
        _createOrder_arg1OrderListVal1Payment.setCardHolderName("CardHolderName2138940798");
        _createOrder_arg1OrderListVal1Payment.setCardNumber("CardNumber1557831959");
        edu.luc.comp433.service.Customer _createOrder_arg1OrderListVal1PaymentCustomer = new edu.luc.comp433.service.Customer();
        _createOrder_arg1OrderListVal1PaymentCustomer.setId(Short.valueOf((short)27199));
        _createOrder_arg1OrderListVal1PaymentCustomer.setLogin("Login1482327739");
        _createOrder_arg1OrderListVal1PaymentCustomer.setName("Name1400021792");
        _createOrder_arg1OrderListVal1PaymentCustomer.setPassword("Password656731311");
        _createOrder_arg1OrderListVal1Payment.setCustomer(_createOrder_arg1OrderListVal1PaymentCustomer);
        _createOrder_arg1OrderListVal1Payment.setExpirationMonth(180653653);
        _createOrder_arg1OrderListVal1Payment.setExpirationYear(912772594);
        _createOrder_arg1OrderListVal1Payment.setId(Short.valueOf((short)26799));
        _createOrder_arg1OrderListVal1Payment.setSecurityCode(44236372);
        _createOrder_arg1OrderListVal1.setPayment(_createOrder_arg1OrderListVal1Payment);
        edu.luc.comp433.service.OrderStatus _createOrder_arg1OrderListVal1Status = edu.luc.comp433.service.OrderStatus.CANCELED;
        _createOrder_arg1OrderListVal1.setStatus(_createOrder_arg1OrderListVal1Status);
        _createOrder_arg1OrderList.add(_createOrder_arg1OrderListVal1);
        _createOrder_arg1.getOrderList().addAll(_createOrder_arg1OrderList);
        _createOrder_arg1.setState("State1974070305");
        _createOrder_arg1.setStreet("Street-946857252");
        _createOrder_arg1.setZipcode(-741817400);
        java.util.List<edu.luc.comp433.service.Book> _createOrder_arg2 = new java.util.ArrayList<edu.luc.comp433.service.Book>();
        edu.luc.comp433.service.Book _createOrder_arg2Val1 = new edu.luc.comp433.service.Book();
        _createOrder_arg2Val1.setAuthor("Author-181432933");
        _createOrder_arg2Val1.setId(Short.valueOf((short)31902));
        _createOrder_arg2Val1.setPrice(new java.math.BigDecimal("-7413707759968596434.3482588851960488007"));
        _createOrder_arg2Val1.setTitle("Title-1278217528");
        _createOrder_arg2.add(_createOrder_arg2Val1);
        edu.luc.comp433.service.Payment _createOrder_arg3 = new edu.luc.comp433.service.Payment();
        _createOrder_arg3.setAmount(new java.math.BigDecimal("5170483994789132868.1858183310752654058"));
        _createOrder_arg3.setCardHolderName("CardHolderName1614696980");
        _createOrder_arg3.setCardNumber("CardNumber1458014870");
        edu.luc.comp433.service.Customer _createOrder_arg3Customer = new edu.luc.comp433.service.Customer();
        _createOrder_arg3Customer.setId(Short.valueOf((short)31365));
        _createOrder_arg3Customer.setLogin("Login886061451");
        _createOrder_arg3Customer.setName("Name-1295206435");
        _createOrder_arg3Customer.setPassword("Password-155737265");
        _createOrder_arg3.setCustomer(_createOrder_arg3Customer);
        _createOrder_arg3.setExpirationMonth(-959544451);
        _createOrder_arg3.setExpirationYear(-1105033923);
        _createOrder_arg3.setId(Short.valueOf((short)24565));
        _createOrder_arg3.setSecurityCode(369179054);
        java.lang.Short _createOrder__return = port.createOrder(_createOrder_arg0, _createOrder_arg1, _createOrder_arg2, _createOrder_arg3);
        System.out.println("createOrder.result=" + _createOrder__return);


        }
        {
        System.out.println("Invoking checkOrderStatus...");
        java.lang.Short _checkOrderStatus_arg0 = Short.valueOf((short)-6229);
        edu.luc.comp433.service.OrderStatus _checkOrderStatus__return = port.checkOrderStatus(_checkOrderStatus_arg0);
        System.out.println("checkOrderStatus.result=" + _checkOrderStatus__return);


        }
        {
        System.out.println("Invoking cancelOrder...");
        java.lang.Short _cancelOrder_arg0 = Short.valueOf((short)3872);
        java.lang.Boolean _cancelOrder__return = port.cancelOrder(_cancelOrder_arg0);
        System.out.println("cancelOrder.result=" + _cancelOrder__return);


        }

        System.exit(0);
    }

}
