
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package edu.luc.comp433.service;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2014-09-30T13:37:42.631-05:00
 * Generated source version: 2.7.12
 * 
 */

@javax.jws.WebService(
                      serviceName = "OrderServiceImplService",
                      portName = "OrderServiceImplPort",
                      targetNamespace = "http://impl.service.comp433.luc.edu/",
                      wsdlLocation = "http://localhost:8080/project2/Order?wsdl",
                      endpointInterface = "edu.luc.comp433.service.OrderService")
                      
public class OrderServiceImpl implements OrderService {

    private static final Logger LOG = Logger.getLogger(OrderServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see edu.luc.comp433.service.OrderService#createOrder(edu.luc.comp433.service.Customer  arg0 ,)edu.luc.comp433.service.Address  arg1 ,)java.util.List<edu.luc.comp433.service.Book>  arg2 ,)edu.luc.comp433.service.Payment  arg3 )*
     */
    public java.lang.Short createOrder(edu.luc.comp433.service.Customer arg0,edu.luc.comp433.service.Address arg1,java.util.List<edu.luc.comp433.service.Book> arg2,edu.luc.comp433.service.Payment arg3) { 
        LOG.info("Executing operation createOrder");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        System.out.println(arg3);
        try {
            java.lang.Short _return = Short.valueOf((short)23516);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see edu.luc.comp433.service.OrderService#checkOrderStatus(java.lang.Short  arg0 )*
     */
    public edu.luc.comp433.service.OrderStatus checkOrderStatus(java.lang.Short arg0) { 
        LOG.info("Executing operation checkOrderStatus");
        System.out.println(arg0);
        try {
            edu.luc.comp433.service.OrderStatus _return = edu.luc.comp433.service.OrderStatus.PROCESSING;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see edu.luc.comp433.service.OrderService#cancelOrder(java.lang.Short  arg0 )*
     */
    public java.lang.Boolean cancelOrder(java.lang.Short arg0) { 
        LOG.info("Executing operation cancelOrder");
        System.out.println(arg0);
        try {
            java.lang.Boolean _return = Boolean.valueOf(false);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
