
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package edu.luc.comp433.service;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2014-09-30T14:03:04.540-05:00
 * Generated source version: 2.7.12
 * 
 */

@javax.jws.WebService(
                      serviceName = "PaymentServiceImplService",
                      portName = "PaymentServiceImplPort",
                      targetNamespace = "http://impl.service.comp433.luc.edu/",
                      wsdlLocation = "http://localhost:8080/project2/Payment?wsdl",
                      endpointInterface = "edu.luc.comp433.service.PaymentService")
                      
public class PaymentServiceImpl implements PaymentService {

    private static final Logger LOG = Logger.getLogger(PaymentServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see edu.luc.comp433.service.PaymentService#findPaymentById(java.lang.Short  arg0 )*
     */
    public edu.luc.comp433.service.Payment findPaymentById(java.lang.Short arg0) { 
        LOG.info("Executing operation findPaymentById");
        System.out.println(arg0);
        try {
            edu.luc.comp433.service.Payment _return = new edu.luc.comp433.service.Payment();
            _return.setAmount(new java.math.BigDecimal("-795054775652465746.4312669514293564753"));
            _return.setCardHolderName("CardHolderName-1103287474");
            _return.setCardNumber("CardNumber1245914653");
            edu.luc.comp433.service.Customer _returnCustomer = new edu.luc.comp433.service.Customer();
            _returnCustomer.setId(Short.valueOf((short)-10129));
            _returnCustomer.setLogin("Login-1741981414");
            _returnCustomer.setName("Name-992012860");
            _returnCustomer.setPassword("Password529780900");
            _return.setCustomer(_returnCustomer);
            _return.setExpirationMonth(-140945467);
            _return.setExpirationYear(1549802060);
            _return.setId(Short.valueOf((short)18993));
            _return.setSecurityCode(887541565);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see edu.luc.comp433.service.PaymentService#findPaymentByCustomerId(java.lang.Short  arg0 )*
     */
    public java.util.List<edu.luc.comp433.service.Payment> findPaymentByCustomerId(java.lang.Short arg0) { 
        LOG.info("Executing operation findPaymentByCustomerId");
        System.out.println(arg0);
        try {
            java.util.List<edu.luc.comp433.service.Payment> _return = new java.util.ArrayList<edu.luc.comp433.service.Payment>();
            edu.luc.comp433.service.Payment _returnVal1 = new edu.luc.comp433.service.Payment();
            _returnVal1.setAmount(new java.math.BigDecimal("3151255963651753237.6822460332933199917"));
            _returnVal1.setCardHolderName("CardHolderName-1835588939");
            _returnVal1.setCardNumber("CardNumber-924102855");
            edu.luc.comp433.service.Customer _returnVal1Customer = new edu.luc.comp433.service.Customer();
            _returnVal1Customer.setId(Short.valueOf((short)3129));
            _returnVal1Customer.setLogin("Login-1286906264");
            _returnVal1Customer.setName("Name-1803393647");
            _returnVal1Customer.setPassword("Password-843497357");
            _returnVal1.setCustomer(_returnVal1Customer);
            _returnVal1.setExpirationMonth(272275180);
            _returnVal1.setExpirationYear(-1685830093);
            _returnVal1.setId(Short.valueOf((short)-8660));
            _returnVal1.setSecurityCode(-875949636);
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
