
package edu.luc.comp433.service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import edu.luc.comp433.service.impl.PaymentServiceImplService;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2014-09-30T14:03:04.409-05:00
 * Generated source version: 2.7.12
 * 
 */
public final class PaymentService_PaymentServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.service.comp433.luc.edu/", "PaymentServiceImplService");

    private PaymentService_PaymentServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = PaymentServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        PaymentServiceImplService ss = new PaymentServiceImplService(wsdlURL, SERVICE_NAME);
        PaymentService port = ss.getPaymentServiceImplPort();  
        
        {
        System.out.println("Invoking findPaymentById...");
        java.lang.Short _findPaymentById_arg0 = Short.valueOf((short)-17060);
        edu.luc.comp433.service.Payment _findPaymentById__return = port.findPaymentById(_findPaymentById_arg0);
        System.out.println("findPaymentById.result=" + _findPaymentById__return);


        }
        {
        System.out.println("Invoking findPaymentByCustomerId...");
        java.lang.Short _findPaymentByCustomerId_arg0 = Short.valueOf((short)-5013);
        java.util.List<edu.luc.comp433.service.Payment> _findPaymentByCustomerId__return = port.findPaymentByCustomerId(_findPaymentByCustomerId_arg0);
        System.out.println("findPaymentByCustomerId.result=" + _findPaymentByCustomerId__return);


        }

        System.exit(0);
    }

}
