package edu.luc.comp433.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2014-09-30T14:03:04.600-05:00
 * Generated source version: 2.7.12
 * 
 */
@WebService(targetNamespace = "http://service.comp433.luc.edu/", name = "PaymentService")
@XmlSeeAlso({ObjectFactory.class})
public interface PaymentService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findPaymentById", targetNamespace = "http://service.comp433.luc.edu/", className = "edu.luc.comp433.service.FindPaymentById")
    @WebMethod
    @ResponseWrapper(localName = "findPaymentByIdResponse", targetNamespace = "http://service.comp433.luc.edu/", className = "edu.luc.comp433.service.FindPaymentByIdResponse")
    public edu.luc.comp433.service.Payment findPaymentById(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Short arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findPaymentByCustomerId", targetNamespace = "http://service.comp433.luc.edu/", className = "edu.luc.comp433.service.FindPaymentByCustomerId")
    @WebMethod
    @ResponseWrapper(localName = "findPaymentByCustomerIdResponse", targetNamespace = "http://service.comp433.luc.edu/", className = "edu.luc.comp433.service.FindPaymentByCustomerIdResponse")
    public java.util.List<edu.luc.comp433.service.Payment> findPaymentByCustomerId(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Short arg0
    );
}
